config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "projects#index"

  get "/about" => "home#about"
  get "/faves" => "home#faves"
  
  resources :projects do 
    resources :tasks
    resources :discussions
    resources :joiners, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :discussions do
    resources :comments
  end
  

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

  belongs_to :user
  belongs_to :project 
  has_many :comments, dependent: :destroy
  validates :title, presence: true

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :find_project
  before_action :authenticate_user!

  def create
    @discussion = Discussion.new discussion_params 
    @discussion.project = @project
    @discussion.user = current_user
    if @discussion.save
      redirect_to @project, notice: "Made new discussion!"
    else
      flash[:alert] = "Please correct your disccussion params!"
      redirect_to project_path(@project, discussion: discussion_params)
    end
  end

  #def show
   # @discussion = @project.discussions.find(params[:id]) 
   # @comment = Comment.new
  #end
 
  def edit
    @discussion = @project.discussions.find(params[:id]) 
  end

  def update
    @discussion = @project.discussions.find(params[:id]) 
    if @discussion.update(discussion_params) 
      redirect_to project_path(@project), notice: "Updated successfully"
    else
      flash.now[:alert] = "Update failed"
      render "/discussions/edit"
    end
  end

  def destroy
    @discussion = @project.discussions.find(params[:id]) 
    if @discussion.destroy && @discussion.user == current_user
      redirect_to @project, notice: "Discussion deleted"
    else
      flash.now[:alert] = "Failed to delete discussion!"
      render "/projects/show"
    end
  end

  private 
    def discussion_params
      params.require(:discussion).permit([:title, :body])
    end
    def find_project 
      @project = Project.find(params[:project_id])
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussion.html.haml
.well
  %h3 Discussion: #{ discussion.title }
  %h5 Body: #{ discussion.body }
  %h5 Posted by : #{ discussion.user.first_name }
  %br
  =link_to "edit", edit_project_discussion_path(@project, discussion)  
  =link_to "delete", project_discussion_path(@project, discussion), method: :delete  
  %h4 Add cmnt!
  = render partial: "/comments/form", locals: {discussion: discussion} 
  %h5 Comments for #{ discussion.title } 
  .comments_list
  - discussion.comments.each do |comment|
    = render "/comments/comment", discussion: discussion, comment: comment
%hr

app/views/discussions/_form.html.haml
= simple_form_for [@project, @discussion] do |f|
  = f.input :title
  = f.input :body
  %p
    = f.submit (@discussion.persisted? ? "Update" : "Create"), class: "btn btn-info"
 

app/views/discussions/edit.html.haml
.well
  %h1 Editing Discussion for #{@discussion.project.title}
  %br
  =render "form"
  
 