config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "projects#index"

  get "/about" => "home#about"
  get "/faves" => "home#faves"
  
  resources :projects do 
    resources :tasks
    resources :discussions
    resources :joiners, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :discussions do
    resources :comments
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :discussion
  validates_presence_of :body

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_discussion

  def create
    @comment = Comment.new(comment_params) 
    #@project = @discussion.project
    @comment.discussion = @discussion 
    @comment.user = current_user
    respond_to do |f|
    if @comment.save
      unless @discussion.user == current_user
        CommentMailer.delay.notify_discussion_owner(@comment)
      end
      f.js { render }
      f.html { redirect_to @project, notice: "Cmnted on page" }
    else
      f.js { render }
      f.html { flash[:alert] = "plz include a comment body!"
      redirect_to project_path(@project, comment: comment_params)
      }
    end 
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = @discussion.comments.find(params[:id])
    @project = @discussion.project
    if @comment.user == current_user && @comment.update(comment_params) 
      redirect_to @project, notice: "Updated successfully"
    else
      flash.now[:alert] = "You can't update this cmnt!"
      render "/comments/edit"
    end
  end
  def destroy
    @comment = @discussion.comments.find(params[:id]) 
    @project = @discussion.project
    respond_to do |f|
    if @comment.user == current_user && @comment.destroy
      f.js { render }
      f.html { redirect_to @project, notice: "cmnt deleted" }
    else
      f.js { render }
      f.html { flash[:alert] = "You cant destroy this comment!"
      redirect_to project_path(@project)
      }
    end
    end 
  end

  private 
    def comment_params
      params.require(:comment).permit([:body])
    end

    def find_discussion 
      @discussion = Discussion.find(params[:discussion_id])
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.a-cmnt-div{:style => "border-bottom: 2px solid #aaa", id: dom_id(comment)}
  %br
  = comment.body
  #h7 Posted by: #{comment.user.first_name if comment.user.present?}
  = link_to "Edit", edit_discussion_comment_path(discussion, comment) 
  = link_to "Delete", discussion_comment_path(discussion, comment), method: :delete, remote: true
  %br

app/views/comments/_form.html.haml
= simple_form_for [ discussion, (@comment || Comment.new)], remote: true  do |f|
  = f.input :body
  %p
    = f.submit (@comment.persisted? ? "Update" : "Create"), class: "btn btn-info"
 

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
  $("#new_comment").html("<%= j render partial: "/comments/form", locals: {discussion: @discussion } %>");
<% else %>
  $(".comments_list").prepend("<%= j render partial: '/comments/comment', locals: {comment: @comment, discussion: @discussion} %>");
  <% @comment = Comment.new %>
  $("#comment_body").val("");
<% end %>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut();

app/views/comments/edit.html.haml
= simple_form_for [@discussion, (@comment || Comment.new)] do |f|
  = f.input :body
  %p
    = f.submit "Update", class: "btn btn-info"
 