config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "projects#index"

  get "/about" => "home#about"
  get "/faves" => "home#faves"
  
  resources :projects do 
    resources :tasks
    resources :discussions
    resources :joiners, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :discussions do
    resources :comments
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  
  validates :title, presence: true, uniqueness: true 
  
  has_many :joiners, dependent: :destroy
  has_many :joined_users, through: :joiners, source: :user
  
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  
  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :find_project, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show] 
  
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params) 
    @project.user = current_user
    if @project.save
      redirect_to projects_path, notice: "Congrats, you have initialized a project!"
    else
      flash.now[:alert] = "Sorry something went wrong!"
      render :new  
    end
  end

  def show
    if params[:task]
      @task = Task.new(params.require(:task).permit([:title, :body, :done, :due_date]))
    else
      @task = Task.new
    end
    if params[:discussion]
      @discussion = Discussion.new(params.require(:discussion).permit([
                                                    :title, :body]))
    else 
      @discussion = Discussion.new
    end
    if params[:comment]
      @comment = Comment.new(params.require(:comment).permit([:body]))
    else
      @comment = Comment.new
    end
  end

  def edit
  end

  def update
    if @project.update project_params 
      redirect_to @project, notice: "Updated successfully"
    else
      flash.now[:alert] = "Update failed"
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: "Project deleted"
    else
      flash.now[:alert] = "Failed to delete!"
      render :show
    end
  end

  private 
    def find_project
      @project = Project.find(params[:id])
    end
    def project_params
      params.require(:project).permit(:title, :description,
                                      :due_date, { joined_user_ids: []},
                                      {tag_ids: []})
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
.well  
  = simple_form_for @project, html: { class: 'form-horizontal' } do |f|
    = f.input :title, label: "Title"
    = f.input :description, label: "Description"
    %p 
      = f.label :ends_on
      = f.date_field :due_date
    = f.label :joiner_ids, "Select Memebers"
    %br
    = f.collection_check_boxes :joined_user_ids, User.all, :id, :full_name
    %br
    = f.label :tag_ids, "Select Tags"
    %br
    = f.collection_check_boxes :tag_ids, Tag.all, :id, :name
    %br
    = f.submit (@project.persisted? ? "Update" : "Create"), class: "btn btn-info"

app/views/projects/edit.html.haml
%h1 Editing project #{ @project.title }
= render "form"

app/views/projects/index.html.haml
- @projects.each do |p|
  .droopy.well.col-md-12
    %h2 #{ link_to p.title, project_path(p) }
    %p Description: #{ p.description }
    %p Created by: #{ p.user.full_name }
    - if p.due_date.present? 
      %p Due in #{ time_ago_in_words(p.due_date) } 

app/views/projects/new.html.haml
%h1 Projects#new
= render 'form'

app/views/projects/show.html.haml
.well
  %h1 #{ @project.title }
  -@project.tags.each do |tag|
    %b #{" #" + tag.name}
  %h5 Description: #{ @project.description }
  %h6 Due in #{ standard_date(@project.due_date) }
  %h6 Created by #{ @project.user.first_name }
  = link_to "Edit", edit_project_path(@project)
  |
  = link_to "Delete", @project, method: :delete, data: { confirm: "Sure?" }
  %br
  %br
  - if user_signed_in? && current_user.has_faved?(@project) 
    - @favourite = current_user.favourites.find_by_project_id(@project) 
    = link_to "Unfavourite", project_favourite_path(@project, @favourite), class: "btn btn-danger", method: :delete
  - else
    = link_to "Favourite!", project_favourites_path(@project), class: "btn btn-primary", method: :post 

  %h5 Project Members: 
  -@project.joined_users.each do |member|
    = member.full_name + " | "
  %br
.well
  %h2 Add a task
  = render "/tasks/form"
  %br
  %h2 The task wall
  .well.tasks{style: "margin-bottom: 200px;"}
    - @project.tasks.each do |task|
      = render "/tasks/task", task: task 
    %br
.well  
  %h2 Add Discussion
  = render "/discussions/form"
  
  %br
  %h2 All Discussions
   
  - @project.discussions.each do |discussion|
    = render "/discussions/discussion", discussion: discussion
  
  %br  
  